# Generated by Django 5.1.4 on 2025-01-13 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='signature',
            field=models.CharField(default='Aspire to have no desire', max_length=140),
        ),
    ]
